<a href="https://colab.research.google.com/github/Sjinjutha/DADS6003/blob/main/Homework1_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ข้อ 1 Normal Equation**

In [1]:
import numpy as np
import pandas as pd

x = np.array([2,5,1,8])
y = np.array([12,9,6,7])
x_b = np.c_[np.ones((x.shape[0],1)),x]

#call inverse function from linear algebra module
theta_best = np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y)
print("theta = ", theta_best)

theta =  [ 9.16666667 -0.16666667]


**ข้อ 2 Batch GD**

In [2]:
x = pd.DataFrame(
    {
    'x1' : [2,5,1,8],
    'x2' : [3,9,4,5],
    'x3' : [6,7,2,3],
    }
)
y = np.array([12,9,6,7])
x_b = np.c_[np.ones((4,1)),x]

theta_best = np.linalg.inv(x_b.T.dot(x_b)).dot(x_b.T).dot(y)
print("theta from normal equation = ", theta_best)

import random
import sklearn
from scipy import stats

def cost_function(theta, x, y, m):
    
    y_predict = theta.T.dot(x.T)
    #print("y_predict ",y_predict)
    error = np.sum((y_predict-y)**2)
    #print("error ", error)
    return error

def gradient_descent(alpha, x, y, ep=0.0000001, max_iter=3):

    converged = False
    iter = 0
    m = x.shape[0] # number of samples

    # initial theta
    t = np.ones((x.shape[0],1))
    #t = np.ones((x.shape[1],1))
    #print("t ", t)
  
    # total error, J(theta)
    J = cost_function(t,x,y,m)
    #print("Iteration 0 --> J=",J," t0=",t0," t1=",t1)

    # Iterate Loop
    while not converged:
        
        #print("theta.shape ",t.shape)
        #print("x.shape ",x.shape)
        y_predict = t.T.dot(x.T)
        
        error = y_predict-y
        grad = x.T.dot(error.T)

        print(f"\nIteration: {iter+1}")
        t = t - alpha * (1/m) * (grad)
        print(f"t0 = {t[0]}, t1 = {t[1]}, t2 = {t[2]}, t3 = {t[3]}")
        
        # error
        e = cost_function(t,x,y,m)
        
        if abs(J-e) <= ep:
            print("Converged, iterations: ", iter, "/", max_iter)
            converged = True
    
        J = e   # update error s
        iter += 1  # update iter
    
        if iter == max_iter:
            print('\nMax iterations exceeded!')
            converged = True

    return t


if __name__ == '__main__':
    
    alpha = 0.05 # learning rate
    
    theta_bgd = gradient_descent(alpha, x_b, y, max_iter=3)
    #print ("\ntheta ", theta_bgd)

theta from normal equation =  [ 6.33548387  0.06451613 -0.7483871   1.29677419]

Iteration: 1
t0 = [0.6875], t1 = [-0.8375], t2 = [-1.1875], t3 = [-0.5625]

Iteration: 2
t0 = [1.68390625], t1 = [3.57], t2 = [4.50234375], t3 = [4.37984375]

Iteration: 3
t0 = [-0.85661914], t1 = [-8.66717188], t2 = [-11.04544141], t3 = [-8.37501563]

Max iterations exceeded!


**ข้อ 3 Stochastic GD**

In [3]:
def st_gradient_descent(alpha, x, y, ep=0.0000001, max_iter=3):

    converged = False
    iter = 0
    m = x.shape[0] # number of samples

    # initial theta
    t = np.ones((x.shape[0],1))
   
    # total error, J(theta)
    J = cost_function(t,x,y,m)
  
    i=0
    # Iterate Loop
    while not converged:
        
        row = [2,0,3]        
        X_i = x[row[i],:]
        y_i = y[row[i]].reshape(1,1)

        y_predict = t.T.dot(X_i)
        error = y_predict-y_i
        X_i = X_i.reshape(1,x.shape[1])
        grad = X_i.T.dot(error.T)
        
        #alpha = 0.05 #Learning rate
        decay = alpha/max_iter
        alpha *= 1/(1+decay*iter)
        print("\nlearning schedule = ", alpha)
        
        print(f"Iteration: {iter+1}")
        t = t - alpha * (1/1) * (grad)
        print(f"t0 = {t[0]}, t1 = {t[1]}, t2 = {t[2]}, t3 = {t[3]}")

        # error
        e = cost_function(t,X_i,y_i,m)
        
        if abs(J-e) <= ep:
            print("Converged, iterations: ", iter, "/", max_iter)
            converged = True
    
        J = e   # update error s
        iter += 1  # update iter
        i += 1
        
        if iter == max_iter:
            print('\nMax iterations exceeded!')
            converged = True

    return t


if __name__ == '__main__':

    #x, y = make_regression(n_samples=100, n_features=2, n_informative=1, random_state=0, noise=35)
    #x_b = np.c_[np.ones((x.shape[0],1)),x]
    
    alpha = 0.05 # learning rate

    theta_sgd = st_gradient_descent(alpha, x_b, y, max_iter=3)
    #print ("theta ", theta_sgd)


learning schedule =  0.05
Iteration: 1
t0 = [0.9], t1 = [0.9], t2 = [0.6], t3 = [0.8]

learning schedule =  0.049180327868852465
Iteration: 2
t0 = [1.03278689], t1 = [1.16557377], t2 = [0.99836066], t3 = [1.59672131]

learning schedule =  0.04761904761904762
Iteration: 3
t0 = [0.40710383], t1 = [-3.83989071], t2 = [-2.13005464], t3 = [-0.28032787]

Max iterations exceeded!


**ข้อ 4 Mini-Batch GD**

In [4]:
x = pd.DataFrame(
    {
    'x1' : [2,5,1,8],
    'x2' : [3,9,4,5],
    'x3' : [6,7,2,3],
    }
)
y = np.array([12,9,6,7])
x_b = np.c_[np.ones((4,1)),x]

def mb_gradient_descent(alpha, x, y, ep=0.00000001, max_iter=3):

    converged = False
    iter = 0
    m = x.shape[0] # number of samples

    # initial theta
    t = np.ones((x.shape[0],1))
   
    # total error, J(theta)
    J = cost_function(t,x,y,m)
    
    batch_size = 2
  
    # Iterate Loop
    while not converged:
        
        #shuffle = decease noise
        rand_ind = np.random.permutation(m)
        print(f"\nrand_ind = {rand_ind}")
        x = x[rand_ind]
        y = y[rand_ind]
        
        for i in range(0,m,batch_size):
            print(f"\ni = {i}")
            
            X_i = x[i:i+batch_size]
            print(f"X_i = {X_i}")
            y_i = y[i:i+batch_size]
            print(f"y_i = {y_i}")

            y_predict = t.T.dot(X_i.T)
            error = y_predict-y_i
            grad = X_i.T.dot(error.T)

            print(f"Iteration: {iter+1}")
            t = t - alpha * (1/batch_size) * (grad)
            print(f"t0 = {t[0]}, t1 = {t[1]}, t2 = {t[2]}, t3 = {t[3]}")

            # error
            e = cost_function(t,X_i,y_i,m)

            if abs(J-e) <= ep:
                print("Converged, iterations: ", iter, "/", max_iter)
                converged = True

            J = e   # update error s
            iter += 1  # update iter
            
            if iter == max_iter:
                print('\nMax iterations exceeded!')
                converged = True
                break
    return t
    


if __name__ == '__main__':

    alpha = 0.05 # learning rate

    theta = mb_gradient_descent(alpha, x_b, y, max_iter=3)
    #print ("theta ", theta)


rand_ind = [1 2 3 0]

i = 0
X_i = [[1. 5. 9. 7.]
 [1. 1. 4. 2.]]
y_i = [9 6]
Iteration: 1
t0 = [0.625], t1 = [-0.675], t2 = [-2.125], t3 = [-1.375]

i = 2
X_i = [[1. 8. 5. 3.]
 [1. 2. 3. 6.]]
y_i = [ 7 12]
Iteration: 2
t0 = [1.971875], t1 = [5.9975], t2 = [3.241875], t3 = [4.716875]

rand_ind = [1 3 2 0]

i = 0
X_i = [[1. 1. 4. 2.]
 [1. 2. 3. 6.]]
y_i = [ 6 12]
Iteration: 3
t0 = [0.36276562], t1 = [3.38854687], t2 = [-2.19471875], t3 = [-2.50071875]

Max iterations exceeded!
